export const HOME_SET_GEOJSON = 'HOME_SET_GEOJSON';

export const HOME_SET_LISTMAPS = 'HOME_SET_LISTMAPS';

export const HOME_SET_SINGLEPLAYER = 'HOME_SET_SINGLEPLAYER';
export const HOME_SET_MULTIPLAYER = 'HOME_SET_MULTIPLAYER';
