//
// HOME
//

export const HOME_SET_GEOJSON = 'HOME_SET_GEOJSON';

export const HOME_SET_LISTMAPS = 'HOME_SET_LISTMAPS';

export const HOME_SET_SINGLEPLAYER = 'HOME_SET_SINGLEPLAYER';
export const HOME_SET_MULTIPLAYER = 'HOME_SET_MULTIPLAYER';

export const HOME_SET_HISTORY = 'HOME_SET_HISTORY';

export const HOME_SET_STREAMER_MODE = 'HOME_SET_STREAMER_MODE';
//
// GAME
//
export const GAME_SET_COUNTRIES = 'GAME_SET_COUNTRIES';
export const GAME_SET_LOADING_COUNTRIES = 'GAME_SET_LOADING_COUNTRIES';
